name: Notificar al Completar Tarea

on:
  issues:
    types: [closed]

jobs:
  notify-completion:
    runs-on: ubuntu-latest
    steps:
    - name: Notificar Tarea Completada
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            body: "🎉 La tarea #${{ github.event.issue.number }} ha sido marcada como completada. ¡Buen trabajo! 🚀"
          })
